<a href="https://colab.research.google.com/github/Lucas-Buk/IMT/blob/main/Tratamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bibliotecas**

In [ ]:
# instala biblioteca para leitura de excel e biblioteca gráfica

!pip install xlrd
!pip install -U plotly
# !pip install plotly==4.8.1

# organização da planilha excel

!pip install nltk

# Exportando figuras com melhores resoluções

!pip install -U kaleido

In [ ]:
!add-apt-repository -y ppa:cran/poppler
!apt-get update
!apt-get install -y libpoppler-cpp-dev

In [ ]:
!apt-get install poppler-utils 

In [ ]:
# Importa a biblioteca pandas

import pandas as pd
pd.options.plotting.backend = "plotly"

# Importa biblioteca para conversão de datas

from datetime import datetime

# Bilbioteca gráfica utilizada neste estudo

import plotly.express as px
import plotly.figure_factory as ff

# Importando pacote
import nltk
nltk.download("popular")
import pandas as pd
import numpy as np

# Stemming pt
nltk.download('rslp')

# biblioteca numérica

import scipy.stats as stats
import scipy
from sklearn.metrics import r2_score

In [107]:
# biblioteca numérica
from scipy.interpolate import interp1d
from scipy import stats
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [108]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [109]:
# Diretório de imagens
import os
if not os.path.exists("images"):
    os.mkdir("images")

In [110]:
from scipy.optimize import curve_fit
import math
import matplotlib.pyplot as plt
import matplotlib

# **Funções proprietárias**

In [111]:
#######################################################################

def DataNorm(Acc):

  # Montagem do Kernel

  variavel =  scipy.stats.zscore(Acc, axis=0, ddof=0)
  empilhada = variavel.tolist()
  empilhada += [24+i for i in variavel.tolist() ]
  empilhada += [48+i for i in variavel.tolist() ]
  bins = np.linspace(0,24,24)
  bins = 3*bins.tolist()
  Kernel = stats.gaussian_kde(empilhada)

  Acc_kernel = Kernel(np.linspace(25,49,24))


  return Acc_kernel

#######################################################################

In [112]:
# Polynomial Regression
def polyfit(x, y, degree):
    results = {}

    coeffs = np.polyfit(x, y, degree)
     # Polynomial Coefficients
    results['polynomial'] = coeffs.tolist()

    correlation = np.corrcoef(x, y)[0,1]

     # r
    results['correlation'] = correlation
     # r-squared
    results['determination'] = correlation**2

    return results

**Função de visualização:**

f(a1,a2,a3,... aN, 'acidente', 'bocejo',...'final')

Comando (!)

In [409]:
def graphics_plot(y, name, title, yaxes_title, save=False):

'''
y = [y1, y2, y3, y4]

name = ['y1 name', 'y2 name', 'y3 name', 'y4 name']

title = 'Title'

yaxes_title = ['Title yaxes1', 'Title yaxes2', 'Title yaxes3', 'Title yaxes4']

save = True -> save graphics as image (images/title.eps) '''

  # Create figure with secondary y-axis
  fig = make_subplots(specs=[[{"secondary_y": True}]])

  # Markers
  markers = ['x','star','diamond','circle']

  # Lines
  dash = ['dash','dot','dashdot']

  if len(yaxes_title) == 1:
    on = False
  else:
    on = True

  for i, v in enumerate(y):
    if i==0:
      # Add traces
      fig.add_trace(
          go.Scatter(x=np.linspace(0,24,9),
          y=v, name=name[i],
          marker_symbol=markers[i],
          marker_size=7,
          mode='lines+markers',
          line=dict(color='rgb(0, 0, 0)',
          width=2),),
          # line_shape='spline'),
          secondary_y=False)
      
    else:
      # Add traces
      fig.add_trace(
          go.Scatter(x=np.linspace(0,24,9),
          y=v, name=name[i],
          marker_symbol=markers[i],
          marker_size=7,
          mode='lines+markers',
          line=dict(color='rgb(0, 0, 0)',
          width=2, dash=dash[i-1]),),
          # line_shape='spline'),
          secondary_y=on)
  
  # Add figure title
  fig.update_layout(title_text=title)
  
  # Set x-axis title
  fig.update_xaxes(title_text="Time of day")

  # Set y-axes titles
  if len(yaxes_title) > 1:
    fig.update_yaxes(title_text="<b>"+ yaxes_title[0] +"</b>", secondary_y=False)
    fig.update_yaxes(title_text="<b>"+ yaxes_title[1] +"</b>", secondary_y=True)
  else:
    fig.update_yaxes(title_text="<b>"+ yaxes_title[0] +"</b>", secondary_y=False)

  
  fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='black')
  fig.update_yaxes(showgrid=False, gridwidth=1, gridcolor='black')

  fig.update_xaxes(showline=True, linewidth=2, linecolor='black', mirror=True)
  fig.update_yaxes(showline=True, linewidth=2, linecolor='black', mirror=True)

  fig.update_layout(
      paper_bgcolor='rgba(0,0,0,0)',
      plot_bgcolor='rgba(0,0,0,0)'
  )

  fig.update_layout(
      xaxis=dict(
      tickmode='linear',
      tick0=0,
      dtick=3
  ))

  fig.show()

  if save:
    fig.write_image("images/"+title+".eps")

# **Dados**

In [113]:
## Carrega uma determinada planilha na variável file

# Monitoramento
fileE3  = '/content/drive/MyDrive/Trabalho/KLB_Final/Monitoramento/Monitoramento 2018_2019 E3.xlsx'
fileE5  = '/content/drive/MyDrive/Trabalho/KLB_Final/Monitoramento/Monitoramento E5 - 2019.xlsx'
fileE9  = '/content/drive/MyDrive/Trabalho/KLB_Final/Monitoramento/Monitoramento E9 - Abril 2019 a fevereiro 2020.xlsx'
fileE9r = '/content/drive/MyDrive/Trabalho/KLB_Final/Monitoramento/Monitoramento E9 - Março a Maio 2020.xlsx'
fileCAS = '/content/drive/MyDrive/Trabalho/KLB_Final/Cabine Anti Sono/Cabine Sono.xlsx'
# Ocorrências
fileOCO = '/content/drive/MyDrive/Trabalho/KLB_Final/Ocorrências/Ocorrências_2017_2018_2019.xlsx'
# Turno
fileTurno  = '/content/drive/MyDrive/Trabalho/KLB_Final/Motoristas por turno.xlsx'
# Informações gerais
fileINF = '/content/drive/MyDrive/Trabalho/KLB_Final/Informações Gerais/Informações gerais empresa Código.xlsx'


## Carrega a planilha em um data frame - data
# Monitoramento
dfE31 = pd.read_excel(fileE3)
xls = pd.ExcelFile(fileE3)
dfE3 = pd.read_excel(fileE3, xls.sheet_names[1])

dfE5 = pd.read_excel(fileE5) 
# Arquivo E9 tem mais planilhas internamente
dfE9 = pd.read_excel(fileE9)
xls = pd.ExcelFile(fileE9)
dfE91 = pd.read_excel(fileE9, xls.sheet_names[1])
dfE92 = pd.read_excel(fileE9,  xls.sheet_names[2])
dfCAS = pd.read_excel(fileCAS)
# Ocorrencias
dfOCO = pd.read_excel(fileOCO)
# Turno
dfTurno = pd.read_excel(fileTurno)
# Informações gerais
dfINF = pd.read_excel(fileINF)

In [114]:
dfCAS.head(2)

Colaborador Empresa  ... Escala de Trabalho 2° momento
0          C2      E3  ...                4.0        sim
1          C3      E3  ...                4.0        não

[2 rows x 13 columns]

In [115]:
dfTurno.head(2)

Unnamed: 0 Unnamed: 1  GT  VPP
0         NaN   00:00:00   3  NaN
1         NaN   01:00:00  19  NaN

In [116]:
dfINF.head(2)

Empresa Escala  ... Observação Unnamed: 7
0      E5    4X2  ...        NaN        NaN
1      E5    4X2  ...        NaN        NaN

[2 rows x 8 columns]

Corrigindo, a empresa que realiza monitoramento é a E17 e não a E5, por gentileza alterar.

Então conforme alinhamos, irei coletar as informações das empresas E17 e E9, além da Klabin. Essas empresas são as que tem monitoramento por câmeras. Além dessas, temos os PMT porém eles iniciaram recentemente o monitoramento por câmeras.

Informações sobre o monitoramento:

Monitoramento_2018_2019: alertas de sono detectados pelas câmeras nos veículos Klabin. Iniciou em 07 de 2018, sendo que a implantação em 100% dos veículos foi a partir de fevereiro de 2019. Os alertas são referente as piscada de olho superior a 3 segundos.

Monitoramento_pmt_códigos:  alertas de sono detectados das pequenas e médias transportadoras. Os alertas são referente as piscada de olho superior a 3 segundos. (Desde 20/08/2019)

Dados Monitoramento Empresa E5: alertas de sono da empresa terceira E5 mês 10, avaliam bocejo e fechada de olha, imagens não são tratadas.  (desde o incio do ano)

Dados Monitoramento Empresa E9: alertas de sono da empresa terceira E9 mês 10, imagens são tratadas, dados onde a piscada foi superior a 1,5 segundos e menor que 3 segundo (fadiga Nível 1). (desde mês 03 de 2019).

Consegui contato com as empresas e confirmei a informação referente ao descanso, para as 3 empresas avaliadas o descanso é de 60 horas.

Sobre o monitoramento da empresa E5 acredito que até segunda-feira encaminho a informação.

Primeiramente gostaria de confirmar se recebeu o shipe que encaminhei e se a informação é suficiente.

Entrei em contato com a empresa E9 para entender melhor o que é cada alerta do monitoramento, o Yawn-Warning capta o bocejo, o Atten-Warning é todo e qualquer desvio de atenção, como por exemplo, olhar para o lado, e o Tired é o cansaço, então é quando o motorista fechou o olhou por mais de 1,5 segundos.

Sobre o questionamento sobre a jornada, eles não passaram o quanto em horas seria esses dois dias de descanso, porém as empresas E3 e E9, passaram que é fixa a escala, não alterando quando retorno dos dias de descanso.

Estou aguardando agora o retorno da empresa E5 para passar o restante das informações.

em uma das planilhas temos escala de trabalho classificada como 1,2,3 - O que significam estes números?
Esse número representa qual dia da escala de trabalho o colaborador está. Por exemplo, o colaborador está no segundo dia da escala de trabalho dele.

O que é a medida em segundo momento?
É quando o colaborador precisou repetir o teste de reflexo por algum motivo, mas não temos a informação do motivo.

Escala 4x2 significa 4 dias de trabalho e 2 de descanso?
Isso, exatamente.

Quando você menciona 3 horas extras - significa que todos fazem ou alguns fazem ?
São horas eventuais, mas quando me passaram da frota própria, passaram com essas horas inclusas.

Qual o significado do termo PMT?
Pequenas e Médias Transportadoras.

O que significa o prefixo VPP?existem outras classificações? 
Es letras do prefixo são referentes as empresas, o VPP é Veículo próprio pesado da nossa frota própria.

O que significa Fadiga N1? existem outras classificações? 
Então essa terminologia é utilizada apenas por uma empresa e significa que o colabora fechou os olhos por mais de 1,5 segundos e no caso a mesma empresa tem o N2 que é quando é por mais de 3 segundos. Mas eles enviaram só as informações de N1 por enquanto.

como interpretar as colunas potencial e SAP?
Então o potencial é a classificação que damos as ocorrências, vou te enviar o texto que consta no nosso procedimento, mas é nosso critério para definição do potencial e o número SAP é o número para buscar o relatório dessa ocorrência, mantive para caso precise procurar fica mais fácil.

Texto Procedimento de Classificação de Ocorrência:

Potencialidade: Conceito aplicado para as ocorrências de acidentes e incidentes considerando a suscetibilidade de existir ou acontecer, mas sem a existência real de um determinada de uma perda.

Potencial Leve (PL): Acidente ou Incidente onde não houve potencialidade de gerar nenhuma das lesões citadas no critério total e permanente;

Potencial Grave (PG): Acidente ou Incidente onde tenha gerado ou houve a possibilidade de ocasionar:

 Incapacidade total e permanente;


 Perdas de função;

Ø Amputação total ou parcial nos membros superiores e/ou inferiores (amputação de dedo(s) das mãos com perda total da função de preensão, amputação da mão/pé, amputação do antebraço/braço/perna);

Ø Perda total ou parcial de um órgão pós trauma ou em decorrência de lesão grave;

Ø Perda total ou parcial de função de órgão em decorrência de lesão grave;

Ø Fratura exposta;

Ø Incapacidade total ou parcial permanente por dano neurológico ou motor;

Ø Queimaduras que resultem em sequelas definitivas com restrição de função de membros superiores e inferiores;

Danos estéticos;

Ø Lesão/cicatriz na face ou deformidade visível com aparência, permanência e irreparabilidade pelos meios comuns ou por si mesma, onde o dano estético apreciável causa complexo ou interfere negativamente na vida social com deformidade de mais de 10% da superfície facial ou 25% de qualquer outra parte do corpo (mãos, pés, braços, pernas e tronco).

Potencial Fatal (PF): Acidente ou incidente onde tenha gerado ou houve a potencialidade de fatalidade.

Tempo de empresa está em meses ou anos (tem valores como 86 e 407, estão corretos)?
Está em meses.

Entrei em contato com a empresa E5 e o alerta referente a piscada é de acordo com o número de piscadas por minuto, porém eles não souberem especificar qual seria esse número.

A empresa iria tentar a informação, buscando o fornecedor mas ainda não obtive nenhum retorno.

Verifiquei alguns pontos para ajuste:

- No campo autores, aparece a legenda “1” para meu nome e da Clara, porém na legenda a Klabin está como “c”.

- Ainda referente aos autores, segue meu nome completo para atualizar: Verônica Marques Lopes

- Na linha “94”, está descrito que a empresa E5 dispõem de 3 sistemas de fadiga, porém conforme descrito na sequência, são apenas 2, bocejo e olho fechado.

- Ajustar descrição do alerta referente a E5: número de piscadas por minuto.

- Desta forma, na linha “98”, ajustar que o alerta referente a Eye closed, considera critérios diferentes, para as empresas E5 e E9.


# **Tratamento de dados**



1.   motoristas em cada hora cheia - E3, E5 e E9
2.   acidentes em cada hora cheia - madeira
3.   eventos em cada hora cheia: bocejo, fadiga, atenção, tired,...



## **Ocorrências**

In [117]:
dfOCO.head(2)

CLASSIFICAÇÃO EMPRESA  ... PRESSA PARA CONCLUIR O TRABALHO DESCRIÇÃO 
0           IBP      E3  ...                             NaN        NaN
1           IBP      E3  ...                             NaN        NaN

[2 rows x 37 columns]

In [118]:
dfOCO.columns

Index(['CLASSIFICAÇÃO', 'EMPRESA', 'GERÊNCIA', 'COORDENAÇÃO ', 'SUB ÁREA',
       'NOME', 'CARGO', 'TEMPO DE EMPRESA', 'IDADE', '\nDATA DA OCORRÊNCIA',
       'DIA DA SEMANA', 'HORA', ' \nLOCAL DA OCORRÊNCIA', 'QUALIDADE PISTA',
       'CARACTERISTICA PISTA', 'SINALIZAÇÃO', 'CLIMA', 'PREFIXO', 'MODELO',
       'CARREGADO', 'TIPO ', 'DETALHAMENTO', 'POTENCIAL', 'SAP', 'DIA ESCALA',
       'ESCALA', 'JORNADA ', 'TEMPO DECORRIDO', 'DORMIU BEM?',
       'PRÓXIMO PERIODO DE FÉRIAS OU FERIADO', 'ALIMENTOU', 'PROBLEMAS SAÚDE ',
       'USO MEDICAMENTO', 'USO ALCOOL/DROGA', 'PRESSÃO',
       'PRESSA PARA CONCLUIR O TRABALHO', 'DESCRIÇÃO '],
      dtype='object')

In [119]:
dfOCO['TIPO '].value_counts()

TRANSPORTE DE MADEIRA              224
VEÍCULO DE LOCOMOÇÃO DE PESSOAS    102
TRANSPORTE GERAL                    52
TRANSPORTE DE MADEIRA                4
Name: TIPO , dtype: int64

In [120]:
# Ocorrências
dfOCO = pd.read_excel(fileOCO)
dfOCO = dfOCO.dropna(subset=['EMPRESA'])
dfOCO = dfOCO.dropna(subset=['TIPO '])
dfOCO['HorarioAcidente'] = pd.to_datetime(dfOCO['HORA'], format='%H:%M:%S').dt.hour
dfOCO.set_index('HORA',drop=True,inplace=True)
dfOCO.head()

CLASSIFICAÇÃO  ... HorarioAcidente
HORA                    ...                
15:00:00           IBP  ...              15
21:40:00           IAP  ...              21
13:51:00           IBP  ...              13
21:45:00           IAP  ...              21
16:51:00           IBP  ...              16

[5 rows x 37 columns]

In [121]:
TM = (dfOCO['TIPO '] == 'TRANSPORTE DE MADEIRA') | (dfOCO['TIPO '] == 'TRANSPORTE DE MADEIRA ')

dfOCO_TM = dfOCO[TM]
dfOCO_TM.EMPRESA.value_counts()

E3     48
E9     42
E2     28
E7     21
E5     19
E4     16
E12    13
E16     9
E1      8
E13     5
E19     3
E23     3
E26     2
E32     2
E33     1
E31     1
E34     1
E22     1
E14     1
E36     1
E30     1
E25     1
Name: EMPRESA, dtype: int64

In [122]:
E3 = (dfOCO_TM['EMPRESA'] == 'E3')
E5 = (dfOCO_TM['EMPRESA'] == 'E5')
E9 = (dfOCO_TM['EMPRESA'] == 'E9')

dfOCO_TM_E3 = dfOCO_TM[E3]
dfOCO_TM_E5 = dfOCO_TM[E5]
dfOCO_TM_E9 = dfOCO_TM[E9]

print(dfOCO_TM_E3.shape,dfOCO_TM_E5.shape,dfOCO_TM_E9.shape)

(48, 37) (19, 37) (42, 37)


## **E3**

**Motoristas por hora**

In [195]:
dfE3.head(5)

HORA              TIPO     QTDE  ... PONTO REFERÊNCIA DIA DA SEMANA COLABORADOR
0     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sex        C170
1     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sex        C170
2     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sex        C170
3     0  FADIGA MOTORISTA  AYM8091  ...              NaN           qui        C170
4     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sáb         C11

[5 rows x 9 columns]

In [196]:
dfE3['UO'].value_counts()

MADEIRA       2680
TRITREM        631
BIOMASSA       291
PRANCHA        180
RIO BRANCO     147
PÁTIO PUMA      24
KLABIN           1
Name: UO, dtype: int64

In [197]:
dfE3[dfE3['HORA'] == 0]['COLABORADOR'].nunique()

41

In [198]:
dfE3[dfE3['HORA'] == 0].shape

(225, 9)

In [199]:
dfE3_motoristas_hora = pd.DataFrame(dfE3.groupby(by='HORA')['COLABORADOR'].nunique().rename('N° de motoristas'))
dfE3_motoristas_hora

N° de motoristas
HORA                  
0                   41
1                   52
2                   44
3                   40
4                   44
5                   41
6                   36
7                   47
8                   42
9                   35
10                  43
11                  36
12                  40
13                  42
14                  46
15                  35
16                  33
17                  34
18                  18
19                  28
20                  25
21                  29
22                  32
23                  37

In [200]:
dfE3['HORA'].hist(nbins=24)

**Eventos por hora**

In [201]:
dfE3.head(2)

HORA              TIPO     QTDE  ... PONTO REFERÊNCIA DIA DA SEMANA COLABORADOR
0     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sex        C170
1     0  FADIGA MOTORISTA  AYM8091  ...              NaN           sex        C170

[2 rows x 9 columns]

In [202]:
dfE3.shape

(3954, 9)

In [203]:
dfE3.TIPO.unique()

array(['FADIGA MOTORISTA'], dtype=object)

In [204]:
dfE3['TIPO'].value_counts()

FADIGA MOTORISTA    3954
Name: TIPO, dtype: int64

In [205]:
dfE3_fad = dfE3.HORA.value_counts().rename('Fadiga').sort_index()
dfE3_fad

0     225
1     357
2     278
3     267
4     274
5     202
6     131
7     133
8     146
9     147
10    240
11    166
12    158
13    186
14    162
15    113
16     97
17     97
18     67
19     84
20     69
21     76
22    119
23    160
Name: Fadiga, dtype: int64

**Acidentes por hora**

In [206]:
dfOCO_TM_E3.head(3)

CLASSIFICAÇÃO  ... HorarioAcidente
HORA                    ...                
21:45:00           IAP  ...              21
13:20:00           IBP  ...              13
00:30:00           IBP  ...               0

[3 rows x 37 columns]

In [207]:
dfOCO_TM_E3.CARGO.value_counts()

MOTORISTA                          29
MOTORISTA TRANSPORTE FLORESTAL     14
OPERADOR DE MÁQUINA                 1
OPERADOR MAQUINAS FLORESTAIS II     1
OPERADOR DE MÁQUINA FLORESTAL       1
BOMBEIRO FLORESTAL                  1
MOTORISTA BALDEIO INTERNO           1
Name: CARGO, dtype: int64

In [208]:
dfOCO_TM_E3_moto = dfOCO_TM_E3[(dfOCO_TM_E3.CARGO == 'MOTORISTA') | (dfOCO_TM_E3.CARGO == 'MOTORISTA TRANSPORTE FLORESTAL')]
dfOCO_TM_E3_moto.head(3)

CLASSIFICAÇÃO  ... HorarioAcidente
HORA                    ...                
21:45:00           IAP  ...              21
13:20:00           IBP  ...              13
20:15:00           OEC  ...              20

[3 rows x 37 columns]

In [209]:
dfE3_acid_hora = dfOCO_TM_E3_moto.HorarioAcidente.value_counts().sort_index().rename('Acidentes por hora')
dfE3_acid_hora

0     4
1     1
2     3
3     3
4     1
5     3
6     1
7     1
8     3
9     3
10    2
11    2
12    1
13    4
14    1
15    1
16    2
18    1
20    2
21    2
22    1
23    1
Name: Acidentes por hora, dtype: int64

**DF final E3**

In [210]:
dfE3_final = pd.DataFrame(dfE3_motoristas_hora['N° de motoristas'])
dfE3_final['Fadiga'] = pd.DataFrame(dfE3_fad)
dfE3_final['Acidentes'] = pd.DataFrame(dfE3_acid_hora)
dfE3_final.fillna(0, inplace=True)
dfE3_final['Acidentes'] = dfE3_final.Acidentes.astype('int64')
dfE3_final

N° de motoristas  Fadiga  Acidentes
HORA                                     
0                   41     225          4
1                   52     357          1
2                   44     278          3
3                   40     267          3
4                   44     274          1
5                   41     202          3
6                   36     131          1
7                   47     133          1
8                   42     146          3
9                   35     147          3
10                  43     240          2
11                  36     166          2
12                  40     158          1
13                  42     186          4
14                  46     162          1
15                  35     113          1
16                  33      97          2
17                  34      97          0
18                  18      67          1
19                  28      84          0
20                  25      69          2
21                  29      76          2
22                  32     119          1
23                  37     160          1

### **Visualização**

In [292]:
counts, bins = np.histogram(dfE3['HORA'], bins=range(0, 25, 3))
counts

array([860, 743, 410, 553, 506, 307, 220, 355])

In [293]:
b = np.array(dfE3_final['N° de motoristas'])
b

array([41, 52, 44, 40, 44, 41, 36, 47, 42, 35, 43, 36, 40, 42, 46, 35, 33,
       34, 18, 28, 25, 29, 32, 37])

In [294]:
c = b.reshape((8,3)).sum(axis=1)
c

array([137, 125, 125, 114, 128, 102,  71,  98])

In [296]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E3", yaxes_title = ["Raw", "Rate"])

##**E5**

**Motoristas por hora**

In [230]:
dfE5.head(2)

Nome                DATA                HORA Tipo de Desatenção  Velocidade
0  NaN 2019-01-04 11:46:41 2019-01-04 11:46:41       Olho Fechado          57
1  NaN 2019-01-11 19:11:04 2019-01-11 19:11:04       Olho Fechado          48

In [231]:
dfE5.shape

(69100, 5)

In [232]:
dfE5['Nome'].nunique()

166

In [233]:
dfE5H = pd.read_excel(fileE5)
dfE5H['HORA'] = pd.to_datetime(dfE5['HORA'], format='%Y-%M-%D %H:%M:%S').dt.hour
dfE5H.head()

Nome                DATA  HORA Tipo de Desatenção  Velocidade
0  NaN 2019-01-04 11:46:41    11       Olho Fechado          57
1  NaN 2019-01-11 19:11:04    19       Olho Fechado          48
2  NaN 2019-02-20 02:49:08     2             Bocejo          58
3  NaN 2019-02-21 05:40:30     5             Bocejo          49
4  NaN 2019-02-21 05:54:02     5             Bocejo          41

In [234]:
dfE5H.isnull().sum()

Nome                  45002
DATA                      0
HORA                      0
Tipo de Desatenção        0
Velocidade                0
dtype: int64

In [235]:
#############
dfE5_nomes = dfE5H.dropna()
dfE5_nomes.shape

(24098, 5)

In [236]:
dfE5_nomes[dfE5_nomes.HORA == 5]['Nome'].value_counts().head(10)

C597     276
C950      59
C620      55
C632      46
C923      31
C612      30
C1100     29
C616      28
C417      28
C1071     27
Name: Nome, dtype: int64

In [237]:
dfE5_motoristas_hora = pd.DataFrame(dfE5_nomes.groupby(by='HORA').nunique()['Nome'].rename('N° de motoristas'))
dfE5_motoristas_hora

N° de motoristas
HORA                  
0                   84
1                   87
2                   83
3                   83
4                   80
5                   77
6                   81
7                   90
8                   93
9                   96
10                  97
11                  96
12                  95
13                  92
14                  96
15                  92
16                 100
17                  87
18                  82
19                  70
20                  72
21                  75
22                  86
23                  76

**Eventos por hora**

In [238]:
dfE5H.head(2)

Nome                DATA  HORA Tipo de Desatenção  Velocidade
0  NaN 2019-01-04 11:46:41    11       Olho Fechado          57
1  NaN 2019-01-11 19:11:04    19       Olho Fechado          48

In [239]:
dfE5H['Tipo de Desatenção'].unique()

array(['Olho Fechado', 'Bocejo'], dtype=object)

In [240]:
dfE5H['Tipo de Desatenção'].value_counts()

Bocejo          40900
Olho Fechado    28200
Name: Tipo de Desatenção, dtype: int64

In [241]:
dfE5_of = dfE5H[dfE5H['Tipo de Desatenção'] == 'Olho Fechado']
dfE5_of_final = dfE5_of.HORA.value_counts().rename('Olho fechado').sort_index()
dfE5_of_final

0      278
1      329
2      384
3      473
4      586
5      548
6     1174
7     1902
8     2285
9     2363
10    2164
11    2172
12    2231
13    2341
14    2386
15    2092
16    1780
17    1080
18     419
19     266
20     225
21     212
22     274
23     236
Name: Olho fechado, dtype: int64

In [251]:
dfE5_of_final.sum()

28200

In [249]:
dfE5_b = dfE5H[dfE5H['Tipo de Desatenção'] == 'Bocejo']
dfE5_b_final = dfE5_b.HORA.value_counts().rename('Bocejo').sort_index()
dfE5_b_final

0     1915
1     2133
2     2342
3     2372
4     2362
5     2419
6     2564
7     2122
8     1715
9     1315
10    1199
11    1248
12    1691
13    1757
14    1649
15    1408
16    1190
17    1257
18    1384
19    1187
20    1191
21    1322
22    1583
23    1575
Name: Bocejo, dtype: int64

In [250]:
dfE5_b_final.sum()

40900

**Acidentes por hora**

In [245]:
dfOCO_TM_E5.head(3)

CLASSIFICAÇÃO  ... HorarioAcidente
HORA                    ...                
18:50:00           IAP  ...              18
23:00:00           IAP  ...              23
14:15:00           IAP  ...              14

[3 rows x 37 columns]

In [246]:
dfOCO_TM_E5.CARGO.value_counts()

MOTORISTA                         16
MOTORISTA TRANSPORTE FLORESTAL     2
MOTORISTA                          1
Name: CARGO, dtype: int64

In [247]:
dfE5_acid_hora = dfOCO_TM_E5.HorarioAcidente.value_counts().sort_index().rename('Acidentes por hora')
dfE5_acid_hora

2     1
3     2
4     2
5     2
6     2
10    1
14    1
18    1
19    2
20    2
22    2
23    1
Name: Acidentes por hora, dtype: int64

**DF final E5**

In [252]:
dfE5_final = pd.DataFrame(dfE5_motoristas_hora['N° de motoristas'])
dfE5_final['Olho_fechado'] = pd.DataFrame(dfE5_of_final)
dfE5_final['Bocejo'] = pd.DataFrame(dfE5_b_final)
dfE5_final['Acidentes'] = pd.DataFrame(dfE5_acid_hora)
dfE5_final.fillna(0, inplace=True)
dfE5_final['Acidentes'] = dfE5_final.Acidentes.astype('int64')
dfE5_final

N° de motoristas  Olho_fechado  Bocejo  Acidentes
HORA                                                   
0                   84           278    1915          0
1                   87           329    2133          0
2                   83           384    2342          1
3                   83           473    2372          2
4                   80           586    2362          2
5                   77           548    2419          2
6                   81          1174    2564          2
7                   90          1902    2122          0
8                   93          2285    1715          0
9                   96          2363    1315          0
10                  97          2164    1199          1
11                  96          2172    1248          0
12                  95          2231    1691          0
13                  92          2341    1757          0
14                  96          2386    1649          1
15                  92          2092    1408          0
16                 100          1780    1190          0
17                  87          1080    1257          0
18                  82           419    1384          1
19                  70           266    1187          2
20                  72           225    1191          2
21                  75           212    1322          0
22                  86           274    1583          2
23                  76           236    1575          1

### **Visualização**

In [323]:
dfE5_of.head(3)

Nome                DATA  HORA Tipo de Desatenção  Velocidade
0   NaN 2019-01-04 11:46:41    11       Olho Fechado          57
1   NaN 2019-01-11 19:11:04    19       Olho Fechado          48
16  NaN 2019-02-22 08:39:56     8       Olho Fechado          52

In [324]:
counts, bins = np.histogram(dfE5_of['HORA'], bins=range(0, 25, 3))
counts

array([ 991, 1607, 5361, 6699, 6958, 4952,  910,  722])

In [325]:
b = np.array(dfE5_final['N° de motoristas'])
b

array([ 84,  87,  83,  83,  80,  77,  81,  90,  93,  96,  97,  96,  95,
        92,  96,  92, 100,  87,  82,  70,  72,  75,  86,  76])

In [326]:
c = b.reshape((8,3)).sum(axis=1)
c

array([254, 240, 264, 289, 283, 279, 224, 237])

In [327]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E5 (Olho fechado)", yaxes_title = ["Raw", "Rate"])

In [340]:
dfE5_b.head(3)

Nome                DATA  HORA Tipo de Desatenção  Velocidade
2  NaN 2019-02-20 02:49:08     2             Bocejo          58
3  NaN 2019-02-21 05:40:30     5             Bocejo          49
4  NaN 2019-02-21 05:54:02     5             Bocejo          41

In [341]:
np.histogram(dfE5_b['HORA'], bins=range(0, 25, 1))

(array([1915, 2133, 2342, 2372, 2362, 2419, 2564, 2122, 1715, 1315, 1199,
        1248, 1691, 1757, 1649, 1408, 1190, 1257, 1384, 1187, 1191, 1322,
        1583, 1575]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]))

In [342]:
counts, bins = np.histogram(dfE5_b['HORA'], bins=range(0, 25, 1))
counts

array([1915, 2133, 2342, 2372, 2362, 2419, 2564, 2122, 1715, 1315, 1199,
       1248, 1691, 1757, 1649, 1408, 1190, 1257, 1384, 1187, 1191, 1322,
       1583, 1575])

In [343]:
b = np.roll(counts, 1)
counts = b.reshape((8,3)).sum(axis=1)
counts

array([5623, 7076, 7105, 4229, 4696, 4247, 3828, 4096])

In [344]:
b = np.array(dfE5_final['N° de motoristas'])
b = np.roll(b, 1)
b

array([ 76,  84,  87,  83,  83,  80,  77,  81,  90,  93,  96,  97,  96,
        95,  92,  96,  92, 100,  87,  82,  70,  72,  75,  86])

In [345]:
c = b.reshape((8,3)).sum(axis=1)
c

array([247, 246, 248, 286, 283, 288, 239, 233])

In [346]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E5 (Bocejo)", yaxes_title = ["Raw", "Rate"])

##**E9**

**Motoristas por hora**

In [158]:
dfE91.head(2)

Data da ocorrência        dia        mês  ...    Placa  Motorista Unnamed: 8
0 2019-04-23 22:59:00 2019-04-23 2019-04-23  ...  PLP3I10        NaN        NaN
1 2019-04-23 19:46:00 2019-04-23 2019-04-23  ...  PLP3I10        NaN        NaN

[2 rows x 9 columns]

In [159]:
dfE91.shape

(6722, 9)

In [160]:
dfE91.isnull().sum()

Data da ocorrência       0
dia                      0
mês                      0
Tipo                     0
Velocidade               0
Tratativa             6546
Placa                    0
Motorista             4717
Unnamed: 8            6722
dtype: int64

In [161]:
##############
dfE91_moto = pd.read_excel(fileE9, xls.sheet_names[1])
dfE91_moto.dropna(subset=['Motorista'],inplace=True)
dfE91_moto.shape

(2005, 9)

In [162]:
dfE91_moto.Motorista.nunique()

152

In [163]:
dfE91_moto['HORA'] = pd.to_datetime(dfE91_moto['Data da ocorrência'], format='%Y-%M-%D %H:%M:%S').dt.hour
dfE91_moto.head()

Data da ocorrência        dia        mês  ... Motorista  Unnamed: 8 HORA
4227 2019-10-08 05:57:00 2019-10-08 2019-10-08  ...      C846         NaN    5
4236 2019-10-08 01:18:00 2019-10-08 2019-10-08  ...      C846         NaN    1
4305 2019-10-10 03:53:00 2019-10-10 2019-10-10  ...      C739         NaN    3
4335 2019-10-11 17:10:00 2019-10-11 2019-10-11  ...      C739         NaN   17
4705 2019-10-29 23:45:00 2019-10-29 2019-10-29  ...      C739         NaN   23

[5 rows x 10 columns]

In [164]:
dfE9_motoristas_hora = pd.DataFrame(dfE91_moto.groupby(by='HORA')['Motorista'].nunique().rename('N° de motoristas1'))
dfE9_motoristas_hora

N° de motoristas1
HORA                   
0                    28
1                    38
2                    36
3                    37
4                    34
5                    33
6                    27
7                    26
8                    28
9                    30
10                   24
11                   30
12                   23
13                   24
14                   32
15                   31
16                   27
17                   18
18                   24
19                   19
20                   19
21                   26
22                   33
23                   35

In [165]:
dfE92.head(2)

Data da ocorrência        dia        mês  ...    Placa  Motorista Unnamed: 8
0 2019-12-01 23:59:00 2019-12-01 2019-12-01  ...  CQU5528       C805        NaN
1 2019-12-01 23:10:00 2019-12-01 2019-12-01  ...  QPY2670       C784        NaN

[2 rows x 9 columns]

In [166]:
dfE92.shape

(2895, 9)

In [167]:
dfE92.isnull().sum()

Data da ocorrência       0
dia                      0
mês                      0
Tipo                     0
Velocidade               0
Tratativa             2735
Placa                    0
Motorista               22
Unnamed: 8            2895
dtype: int64

In [168]:
############
dfE92_moto = pd.read_excel(fileE9, xls.sheet_names[2])
dfE92_moto.dropna(subset=['Motorista'],inplace=True)
dfE92_moto.shape

(2873, 9)

In [169]:
dfE92_moto.Motorista.nunique()

145

In [170]:
dfE92_moto['HORA'] = pd.to_datetime(dfE92_moto['Data da ocorrência'], format='%Y-%M-%D %H:%M:%S').dt.hour
dfE92_moto.head()

Data da ocorrência        dia        mês  ... Motorista  Unnamed: 8 HORA
0 2019-12-01 23:59:00 2019-12-01 2019-12-01  ...      C805         NaN   23
1 2019-12-01 23:10:00 2019-12-01 2019-12-01  ...      C784         NaN   23
2 2019-12-01 21:52:00 2019-12-01 2019-12-01  ...      C752         NaN   21
3 2019-12-01 22:22:00 2019-12-01 2019-12-01  ...      C736         NaN   22
4 2019-12-01 21:25:00 2019-12-01 2019-12-01  ...      C805         NaN   21

[5 rows x 10 columns]

In [171]:
###### Posso estar somando o mesmo motorista no 1 e no 2
dfE9_motoristas_hora['N° de motoristas2'] = pd.DataFrame(dfE92_moto.groupby(by='HORA')['Motorista'].nunique())
dfE9_motoristas_hora['N° de motoristas'] = dfE9_motoristas_hora['N° de motoristas1'] + dfE9_motoristas_hora['N° de motoristas2']
dfE9_motoristas_hora

N° de motoristas1  N° de motoristas2  N° de motoristas
HORA                                                        
0                    28                 21                49
1                    38                 41                79
2                    36                 50                86
3                    37                 40                77
4                    34                 28                62
5                    33                 18                51
6                    27                 31                58
7                    26                 33                59
8                    28                 39                67
9                    30                 25                55
10                   24                 27                51
11                   30                 28                58
12                   23                 39                62
13                   24                 38                62
14                   32                 30                62
15                   31                 35                66
16                   27                 30                57
17                   18                 33                51
18                   24                 23                47
19                   19                 17                36
20                   19                 14                33
21                   26                 36                62
22                   33                 43                76
23                   35                 29                64

**Eventos por hora**

In [172]:
dfE91.head(2)

Data da ocorrência        dia        mês  ...    Placa  Motorista Unnamed: 8
0 2019-04-23 22:59:00 2019-04-23 2019-04-23  ...  PLP3I10        NaN        NaN
1 2019-04-23 19:46:00 2019-04-23 2019-04-23  ...  PLP3I10        NaN        NaN

[2 rows x 9 columns]

In [173]:
dfE91H = pd.read_excel(fileE9, xls.sheet_names[1])
dfE91H['HORA'] = pd.to_datetime(dfE91H['Data da ocorrência'], format='%Y-%M-%D %H:%M:%S').dt.hour
dfE91H.head()

Data da ocorrência        dia        mês  ... Motorista  Unnamed: 8 HORA
0 2019-04-23 22:59:00 2019-04-23 2019-04-23  ...       NaN         NaN   22
1 2019-04-23 19:46:00 2019-04-23 2019-04-23  ...       NaN         NaN   19
2 2019-04-24 00:54:00 2019-04-24 2019-04-24  ...       NaN         NaN    0
3 2019-04-24 01:04:00 2019-04-24 2019-04-24  ...       NaN         NaN    1
4 2019-04-24 01:06:00 2019-04-24 2019-04-24  ...       NaN         NaN    1

[5 rows x 10 columns]

In [174]:
dfE91H.Tipo.value_counts()

Yawn-Warning    6149
Tired            573
Name: Tipo, dtype: int64

In [175]:
dfE9_yawn = dfE91H[dfE91H['Tipo'] == 'Yawn-Warning']
dfE9_yawn = dfE9_yawn.HORA.value_counts().rename('Yawn-Warning').sort_index()
dfE9_yawn

0     299
1     282
2     409
3     382
4     492
5     489
6     302
7     185
8     211
9     199
10    182
11    181
12    131
13    144
14    187
15    217
16    219
17    162
18    136
19    170
20    221
21    255
22    336
23    358
Name: Yawn-Warning, dtype: int64

In [176]:
dfE9_yawn.sum()

6149

In [177]:
dfE9_tired = dfE91H[dfE91H['Tipo'] == 'Tired']
dfE9_tired = dfE9_tired.HORA.value_counts().rename('Tired').sort_index()
dfE9_tired

0     10
1     14
2     22
3     24
4     14
5     12
6     18
7     30
8     42
9     38
10    25
11    34
12    14
13    31
14    37
15    28
16    18
17    54
18    16
19     8
20     5
21    12
22    33
23    34
Name: Tired, dtype: int64

In [178]:
dfE9_tired.sum()

573

In [179]:
dfE92.head(2)

Data da ocorrência        dia        mês  ...    Placa  Motorista Unnamed: 8
0 2019-12-01 23:59:00 2019-12-01 2019-12-01  ...  CQU5528       C805        NaN
1 2019-12-01 23:10:00 2019-12-01 2019-12-01  ...  QPY2670       C784        NaN

[2 rows x 9 columns]

In [180]:
dfE92H = pd.read_excel(fileE9, xls.sheet_names[2])
dfE92H['HORA'] = pd.to_datetime(dfE92H['Data da ocorrência'], format='%Y-%M-%D %H:%M:%S').dt.hour
dfE92H.head()

Data da ocorrência        dia        mês  ... Motorista  Unnamed: 8 HORA
0 2019-12-01 23:59:00 2019-12-01 2019-12-01  ...      C805         NaN   23
1 2019-12-01 23:10:00 2019-12-01 2019-12-01  ...      C784         NaN   23
2 2019-12-01 21:52:00 2019-12-01 2019-12-01  ...      C752         NaN   21
3 2019-12-01 22:22:00 2019-12-01 2019-12-01  ...      C736         NaN   22
4 2019-12-01 21:25:00 2019-12-01 2019-12-01  ...      C805         NaN   21

[5 rows x 10 columns]

In [181]:
dfE92H.Tipo.value_counts()

Atten-Warning    2895
Name: Tipo, dtype: int64

In [182]:
dfE9_at = dfE92H.HORA.value_counts().rename('Atten-Warning').sort_index()
dfE9_at

0      44
1     170
2     210
3     274
4      83
5      45
6      91
7     125
8     159
9      95
10    144
11    114
12    185
13    177
14    105
15    118
16    111
17     93
18     46
19     36
20     24
21    145
22    220
23     81
Name: Atten-Warning, dtype: int64

In [183]:
dfE9_at.sum()

2895

**Acidentes por hora**

In [184]:
dfOCO_TM_E9.head(3)

CLASSIFICAÇÃO  ... HorarioAcidente
HORA                    ...                
00:01:00     INCIDENTE  ...               0
01:30:00           IAP  ...               1
02:00:00           IBP  ...               2

[3 rows x 37 columns]

In [185]:
dfOCO_TM_E9.CARGO.value_counts()

MOTORISTA                         38
MOTORISTA TRANSPORTE FLORESTAL     2
MOTORISTA                          2
Name: CARGO, dtype: int64

In [186]:
dfE9_acid_hora = dfOCO_TM_E9.HorarioAcidente.value_counts().sort_index().rename('Acidentes por hora')
dfE9_acid_hora

0     1
1     1
2     2
4     3
5     3
7     1
8     5
9     1
10    1
11    3
13    2
14    2
15    2
17    2
18    2
19    1
20    2
21    1
22    3
23    4
Name: Acidentes por hora, dtype: int64

**DF final E9**

In [187]:
dfE9_final = pd.DataFrame(dfE9_motoristas_hora['N° de motoristas'])
dfE9_final['Yawn'] = pd.DataFrame(dfE9_yawn)
dfE9_final['Tired'] = pd.DataFrame(dfE9_tired)
dfE9_final['Atten-Warning'] = pd.DataFrame(dfE9_at)
dfE9_final['Acidentes'] = pd.DataFrame(dfE9_acid_hora)
dfE9_final.fillna(0, inplace=True)
dfE9_final['Acidentes'] = dfE9_final.Acidentes.astype('int64')
dfE9_final

N° de motoristas  Yawn  Tired  Atten-Warning  Acidentes
HORA                                                         
0                   49   299     10             44          1
1                   79   282     14            170          1
2                   86   409     22            210          2
3                   77   382     24            274          0
4                   62   492     14             83          3
5                   51   489     12             45          3
6                   58   302     18             91          0
7                   59   185     30            125          1
8                   67   211     42            159          5
9                   55   199     38             95          1
10                  51   182     25            144          1
11                  58   181     34            114          3
12                  62   131     14            185          0
13                  62   144     31            177          2
14                  62   187     37            105          2
15                  66   217     28            118          2
16                  57   219     18            111          0
17                  51   162     54             93          2
18                  47   136     16             46          2
19                  36   170      8             36          1
20                  33   221      5             24          2
21                  62   255     12            145          1
22                  76   336     33            220          3
23                  64   358     34             81          4

### **Visualização**

In [350]:
dfE91.shape

(6722, 9)

In [351]:
dfE91H.shape

(6722, 10)

In [356]:
dfE91H.Tipo.value_counts()

Yawn-Warning    6149
Tired            573
Name: Tipo, dtype: int64

In [357]:
dfE91H_yawn = dfE91H[dfE91H.Tipo == 'Yawn-Warning']

In [358]:
counts, bins = np.histogram(dfE91H_yawn['HORA'], bins=range(0, 25, 3))
counts

array([ 990, 1363,  698,  562,  462,  598,  527,  949])

In [359]:
b = np.array(dfE9_final['N° de motoristas'])
print(b)
c = b.reshape((8,3)).sum(axis=1)
print(c)

[49 79 86 77 62 51 58 59 67 55 51 58 62 62 62 66 57 51 47 36 33 62 76 64]
[214 190 184 164 186 174 116 202]


In [360]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E9 (Yawn-Warning)", yaxes_title = ["Raw", "Rate"])

In [361]:
dfE91H_tired = dfE91H[dfE91H.Tipo == 'Tired']

In [362]:
counts, bins = np.histogram(dfE91H_tired['HORA'], bins=range(0, 25, 3))
counts

array([ 46,  50,  90,  97,  82, 100,  29,  79])

In [363]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E9 (Tired)", yaxes_title = ["Raw", "Rate"])

In [390]:
dfE92.shape

(2895, 9)

In [391]:
dfE92H.shape

(2895, 10)

In [392]:
dfE92H.Tipo.value_counts()

Atten-Warning    2895
Name: Tipo, dtype: int64

In [393]:
dfE92H_at = dfE92H[dfE92H.Tipo == 'Atten-Warning']
dfE92H_at.shape

(2895, 10)

In [394]:
counts, bins = np.histogram(dfE92H_at['HORA'], bins=range(0, 25, 3))
counts

array([424, 402, 375, 353, 467, 322, 106, 446])

In [398]:
graphics_plot(y = [counts, counts/c], name = ['Events(raw)', 'Events/Drivers'],
              title = "Events company E9 (Atten-Warning)", yaxes_title = ["Raw", "Rate"],
              save=True)

In [381]:
# fig.write_image("images/AcidentesTotal.eps") ### Salvar imagens

# **Salvar os resultados em csv**

In [376]:
dfE3_final.to_csv('/content/drive/MyDrive/Trabalho/Datasets/E3_final.csv', encoding='utf-8')#, index=False)

In [377]:
df = pd.read_csv('/content/drive/MyDrive/Trabalho/Datasets/E3_final.csv', index_col='HORA')
df.head()

N° de motoristas  Fadiga  Acidentes
HORA                                     
0                   41     225          4
1                   52     357          1
2                   44     278          3
3                   40     267          3
4                   44     274          1